//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolData
{
    using System;
    using System.Collections.Generic;
    
    public partial class SD_OnlineCourse
    {
        public int CourseID { get; set; }
        public string URL { get; set; }
    
        public virtual SD_Course SD_Course { get; set; }
    }
}
