//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolData
{
    using System;
    using System.Collections.Generic;
    
    public partial class SD_Student
    {
        public int PersonID { get; set; }
        protected int year { get; set; }
    
        public virtual SD_Person SD_Person { get; set; }
    }
}
